version: '3'
services:
  postgres:
    image: postgres:11
    ports:
    - "5432:5432"
  email:
    image: djfarrelly/maildev
    ports:
    - 1080:80
  learning-circles:
    build: .
    image: p2pu/learning-circles:local
    links:
    - selenium
    ports:
    - "8000:8000"
    volumes:
    - .:/opt/app
    depends_on:
    - postgres
    - email
    command: /opt/django-venv/bin/python manage.py test
    environment:
    - DATABASE_URL=postgres://lc:password@postgres:5432/lc
    - SECRET_KEY=321
    - BROKER_URL=amqp://guest:guest@rabbitmq//
    - EMAIL_HOST=email
    - COMMUNITY_MANAGER=user@mail.com
    - DEFAULT_FROM_EMAIL=notify@mail.com
    - ADMIN_EMAIL=admin@localhost
    - DEBUG=true
    - RECAPTCHA_SITE_KEY=6Le0DW8bAAAAAJUHXcKkkASxZWMIwDypy1DiBBEX
  frontend:
    image: node:lts-slim
    volumes:
    - .:/opt/app
    working_dir: /opt/app
    command: sh -c "npm i && npm run watch"
  selenium:
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - 5900:5900

