name: Django CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build docker image
      run: docker build -t p2pu/learning-circles .
    - name: start postgres container
      run: docker run -d --name=postgres -e POSTGRES_PASSWORD=password postgres:11
    - name: start selenium container
      run: docker run -d --name=selenium --shm-size="2g" selenium/standalone-chrome:4.0.0-20211102
    - name: run tests
      run: docker run --rm -i --link postgres --link selenium -e DATABASE_URL=postgres://postgres:password@postgres/lc -e SECRET_KEY=abc -e ADMIN_EMAIL=admin@localhost -e RECAPTCHA_SITE_KEY=6Le0DW8bAAAAAJUHXcKkkASxZWMIwDypy1DiBBEX p2pu/learning-circles dockerize -wait tcp://postgres:5432 /opt/django-venv/bin/python /opt/app/manage.py test
